# Generated by Django 2.1.5 on 2019-03-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='manager_id',
        ),
    ]
