# Generated by Django 2.1.5 on 2019-02-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volt_finder', '0002_chargingstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
