# Generated by Django 2.1.5 on 2019-03-08 00:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_finder', '0003_auto_20190308_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
