# Generated by Django 2.1.5 on 2019-03-05 03:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volt_finder', '0003_chargingstation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
