# Generated by Django 2.1.5 on 2019-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_finder', '0004_auto_20190308_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
