version: '3.7'

services:
  db:
    image: mdillon/postgis:9.6
    container_name: db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=SirGeorgeWilliams1515
      - POSTGRES_DB=pg_gis_db
  dj:
    container_name: dj
    build: django-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-server/api_django:/code
    environment:
      - v2go_GOOGLE_API_KEY=AIzaSyDV6tzXNYpZNv0gRL1n778fltpBHUlA2fQ
    ports:
      - "8888:8000"
    depends_on:
      - db
  ng:
    container_name: ng
    build: angular
    ports: 
      - "8080:80"