version: '3.7'

services:

  web:
    build: ./django-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-server:/usr/src/app
    env_file: 
      - django-server/.env_files/.api_dev.env
    ports:
      - "8888:8000"
    depends_on:
      - db

  db:
    image: mdillon/postgis:9.6
    container_name: db
    env_file: 
      - django-server/.env_files/.db_dev.env
    ports:
      - "5433:5432"
    volumes:
      - data_db:/var/lib/postgresql/data
  
volumes:
  data_db: