version: '3.7'

services:
  web:
    build:
      context: ./django-server
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    env_file: .env
    ports:
      - "8888:8000"
    depends_on:
      - db

  frontend:
    image: dukdocker/v2go-angular:alpha
    command: ng serve --host 0.0.0.0
    depends_on:
      - web
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4200:4200

  db:
    image: mdillon/postgis:9.6
    container_name: db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=SirGeorgeWilliams1515
      - POSTGRES_DB=pg_gis_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data: