version: '3.7'

services:

  web:
    build: ./django-server
    # command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    # env_file: django-server/.env
    environment:
      - v2go_GOOGLE_API_KEY=AIzaSyDV6tzXNYpZNv0gRL1n778fltpBHUlA2fQ
      - DEBUG=1
      - SECRET_KEY=@=3v3urk9a=y1=(yjs%r2uabvv@i*3(!#*^br7^5*0$p0wlbwr
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=pg_gis_db
      - SQL_USER=dev_user
      - SQL_PASSWORD=SirGeorgeWilliams1515
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    ports:
      - "8888:8000"
    depends_on:
      - db

  db:
    image: mdillon/postgis:9.6
    # env_file: django-server/.env.db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=SirGeorgeWilliams1515
      - POSTGRES_DB=pg_gis_db
    ports:
      - "5433:5432"
    volumes:
      # - data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  media:
  static:
  # data:
  postgres_data: