version: '3.7'

services:
  db:
    image: mdillon/postgis:9.6
    container_name: db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=SirGeorgeWilliams1515
      - POSTGRES_DB=pg_gis_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: ./django-server
    command: python api_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-server:/code
    environment:
      - v2go_GOOGLE_API_KEY=AIzaSyDV6tzXNYpZNv0gRL1n778fltpBHUlA2fQ
    ports:
      - "8888:8000"
    depends_on:
      - db
  frontend:
    image: dukdocker/v2go-angular:alpha
    # Development ONLY: link volume to live update src/ in container 
    # volumes:  
    #   - ../v2go-frontend:/usr/src/app
    command: ng serve --host 0.0.0.0
    container_name: frontend
    depends_on:
      - web
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200
  
volumes:
  data: