version: '3.7'

services:

  web:
    build: 
      context: ./django-server
      dockerfile: prod.Dockerfile
    command: gunicorn api_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    env_file: 
      - django-server/.env_files/.api_prod.env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: mdillon/postgis:9.6
    container_name: db
    env_file: 
      - django-server/.env_files/.db_prod.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  nginx:
    build: ./nginx
    volumes:
      - media:/usr/src/app/media
      - static:/usr/src/app/static
    ports:
      - 1337:80
    depends_on:
      - web
  
volumes:
  media:
  static:
  postgres_data:
