# Generated by Django 2.1.5 on 2019-03-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_auto_20190316_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_event_nk', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERBED', 'Reserved'), ('UNAVAILABLE', 'Unavailable'), ('OUT OF SERVICE', 'Out of Service')], default='a', max_length=20)),
                ('ev_event_id', models.IntegerField(default=-1)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ChargingStation')),
            ],
        ),
        migrations.CreateModel(
            name='EVEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cs_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volt_reservation.CSEvent')),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EV')),
            ],
        ),
    ]
