# Generated by Django 2.1.5 on 2019-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csevent',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable'), ('OUT OF SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20),
        ),
    ]
