# Generated by Django 2.1.5 on 2019-03-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190321_2052'),
        ('volt_reservation', '0002_auto_20190318_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSEvent',
            new_name='EventCS',
        ),
        migrations.RenameModel(
            old_name='EVEvent',
            new_name='EventEV',
        ),
    ]
