# Generated by Django 2.1.5 on 2019-04-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0003_auto_20190327_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcs',
            old_name='cs_event_nk',
            new_name='nk',
        ),
    ]
