# Generated by Django 2.1.5 on 2019-04-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0004_auto_20190407_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventev',
            old_name='cs_event',
            new_name='event_cs',
        ),
    ]
