# Generated by Django 2.1.5 on 2019-04-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0007_auto_20190409_1815'),
        ('volt_reservation', '0007_auto_20190407_2231'),
    ]

    operations = [
    ]
