# Generated by Django 2.1.5 on 2019-04-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0009_auto_20190409_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcs',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable'), ('OUT_OF_SERVICE', 'Out of Service'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventev',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable'), ('OUT_OF_SERVICE', 'Out of Service'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='RESERVED', max_length=20),
        ),
    ]
