# Generated by Django 2.1.5 on 2019-05-02 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volt_reservation', '0010_auto_20190415_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventev',
            name='ev_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
