# Generated by Django 2.1.5 on 2019-06-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0011_eventev_ev_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcs',
            old_name='endDateTime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='eventcs',
            old_name='startDateTime',
            new_name='start_datetime',
        ),
    ]
