# Generated by Django 2.1.5 on 2019-06-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt_reservation', '0012_auto_20190620_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventev',
            name='ev_owner',
        ),
    ]
