# Generated by Django 2.1.5 on 2019-03-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chargingstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='location',
        ),
    ]
