# Generated by Django 2.1.5 on 2019-03-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('main', '0003_remove_chargingstation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=40)),
                ('manufacturer', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('charger_type', models.CharField(choices=[('a', 'Charger Type A'), ('b', 'Charger Type B'), ('c', 'Charger Type C')], default='a', max_length=20)),
                ('calendar', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='EVOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evehicle',
            name='ev_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EVOwner'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='cs_host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.CSHost'),
        ),
    ]
