# Generated by Django 2.1.5 on 2019-03-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('main', '0005_chargingstation_calendar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EVehicle',
            new_name='EV',
        ),
    ]
