# Generated by Django 2.1.5 on 2019-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190318_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='nk',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
