# Generated by Django 2.1.5 on 2019-03-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190318_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EVOwner',
            new_name='Driver',
        ),
    ]
