# Generated by Django 2.1.5 on 2019-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190318_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cshost',
            name='nk',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nk',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='nk',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
