# Generated by Django 2.1.5 on 2019-03-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190318_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='cs_host',
        ),
    ]
