# Generated by Django 2.1.5 on 2019-03-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_chargingstation_cs_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSHost',
        ),
        migrations.RemoveField(
            model_name='ev',
            name='ev_owner',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
