# Generated by Django 2.1.5 on 2019-04-06 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190321_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='cs_host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
