# Generated by Django 2.1.5 on 2019-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190409_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricvehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
