# Generated by Django 2.1.5 on 2019-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_electricvehicle_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricvehicle',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
