# Generated by Django 2.1.5 on 2019-05-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190424_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='calendar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar'),
        ),
    ]
