# Generated by Django 2.1.5 on 2019-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190504_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
